# -*- coding: utf-8 -*-
"""Lab2 task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ituEDWVrWkvurvx1xi9lNx_B3i2ibMrm
"""

numbers = [12, 45, 7, 89, 23, 56, 3, 78, 34, 10]


total_sum = sum(numbers)
maximum = max(numbers)
minimum = min(numbers)

print("List of numbers:", numbers)
print("Sum:", total_sum)
print("Maximum:", maximum)
print("Minimum:", minimum)

#Add and remove element
numbers.append(20)
numbers.remove(12)
print('Updated list:',numbers)

# acending and decending
print('Ascending:',sorted(numbers))
print('Decending:',sorted(numbers,reverse=True))

"""Matplolib"""



"""Numpy

List

Tuple
"""

#create a tuple
fruits = ('apple','banana','grape')
print('Second element:',fruits[1])
print('last element:',fruits[-1])

#modifying the tuple now
fruits_list = list(fruits)
fruits_list.append('orange')
fruits_list[1] = 'mango'
fruits_list.remove('apple')

# Convert back to tuple
fruits = tuple(fruits_list)
print('Modified tuple:', fruits)

"""Set"""

# Create two sets(list Question # 01)
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

print("Set 1:", set1)
print("Set 2:", set2)

# Union (all unique elements from both sets)
print("Union:", set1 | set2)           # or set1.union(set2)

# Intersection (common elements)
print("Intersection:", set1 & set2)    # or set1.intersection(set2)

# Difference (elements in set1 but not in set2)
print("Difference (set1 - set2):", set1 - set2)



# Create a set ( Question # 02)

my_set = {1, 2, 3, 4, 5}
print("Original Set:", my_set)

# Add a new element
my_set.add(10)   # adds 10 to the set
print("After Adding 10:", my_set)

# Remove an existing element
my_set.remove(3)   # removes element 3
print("After Removing 3:", my_set)

"""Dictionary"""

# Create dictionary with 5 key-value pairs
students = {
    "Ali": 85,
    "Sara": 92,
    "Bilal": 76,
    "Ayesha": 89,
    "Hamza": 95
}

# Print dictionary
print("Student Marks:", students)